module.exports = {
  apps: [
    {
      name: 'api',
      script: 'backend/index.js',
      cwd: '.',
      interpreter: 'node',
      node_args: '--max-old-space-size=256',
      instances: 1,
      exec_mode: 'fork',
      watch: false,
      max_memory_restart: '300M',
      env_production: {
        NODE_ENV: 'production',
        PORT: 3001,
      },
      error_file: './logs/api-error.log',
      out_file: './logs/api-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
    },
    {
      name: 'scheduler',
      script: 'backend/src/workers/schedulerWorker.js',
      cwd: '.',
      interpreter: 'node',
      node_args: '--max-old-space-size=150',
      instances: 1,
      exec_mode: 'fork',
      watch: false,
      max_memory_restart: '200M',
      env_production: {
        NODE_ENV: 'production',
      },
      error_file: './logs/scheduler-error.log',
      out_file: './logs/scheduler-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
    },
    {
      name: 'ai-worker',
      script: 'backend/src/workers/aiWorker.js',
      cwd: '.',
      interpreter: 'node',
      node_args: '--max-old-space-size=500',
      instances: 1,
      exec_mode: 'fork',
      watch: false,
      max_memory_restart: '550M',
      env_production: {
        NODE_ENV: 'production',
      },
      error_file: './logs/ai-worker-error.log',
      out_file: './logs/ai-worker-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
    },
  ],
};
